#!/bin/bash

# Connect to PostgreSQL and execute SQL commands with environment variables
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    CREATE DATABASE $KONG_PG_DATABASE;
    CREATE USER $KONG_PG_USER WITH ENCRYPTED PASSWORD '$KONG_PG_PASSWORD';
    GRANT ALL PRIVILEGES ON DATABASE $KONG_PG_DATABASE TO $KONG_PG_PASSWORD;

    CREATE DATABASE $KONGA_PG_DATABASE;
    CREATE USER $KONGA_PG_USER WITH ENCRYPTED PASSWORD '$KONGA_PG_PASSWORD';
    GRANT ALL PRIVILEGES ON DATABASE $KONGA_PG_DATABASE TO $KONGA_PG_PASSWORD;
EOSQL